import type { MatchState } from '@/lib/types/computed';
import type { Match, Player } from '@/lib/types/models';
import { formatPlayerName } from '@/lib/utils';

function buildTeamLabel(players: Player[]) {
  return players
    .map((player) => formatPlayerName(player.firstName, player.lastName, 'short'))
    .join(' & ');
}

export function countHalvedHoles(matchState: MatchState) {
  return matchState.holeResults.filter((result) => result.winner === 'halved').length;
}

export function findNextIncompleteMatch(currentMatchId: string, sessionMatches: Match[]) {
  const currentIndex = sessionMatches.findIndex((match) => match.id === currentMatchId);

  if (currentIndex < 0) return undefined;

  for (let index = currentIndex + 1; index < sessionMatches.length; index += 1) {
    if (sessionMatches[index].status !== 'completed') {
      return sessionMatches[index];
    }
  }

  for (let index = 0; index < currentIndex; index += 1) {
    if (sessionMatches[index].status !== 'completed') {
      return sessionMatches[index];
    }
  }

  return undefined;
}

export function buildMatchSummaryText({
  matchState,
  teamAName,
  teamBName,
  teamAPlayers,
  teamBPlayers,
  matchUrl,
}: {
  matchState: MatchState;
  teamAName: string;
  teamBName: string;
  teamAPlayers: Player[];
  teamBPlayers: Player[];
  matchUrl?: string;
}) {
  const winnerText =
    matchState.winningTeam === 'halved'
      ? 'Match halved'
      : `${matchState.winningTeam === 'teamA' ? teamAName : teamBName} wins`;

  const base = `⛳ ${winnerText} ${matchState.displayScore}\n${buildTeamLabel(teamAPlayers)} vs ${buildTeamLabel(teamBPlayers)}\nHoles won: ${teamAName} ${matchState.teamAHolesWon} | ${teamBName} ${matchState.teamBHolesWon}\nHalved: ${countHalvedHoles(matchState)}\nCompleted thru hole ${matchState.holesPlayed}`;
  return matchUrl ? `${base}\n\n${matchUrl}` : base;
}

export function buildMatchResultShareText({
  matchState,
  teamAName,
  teamBName,
  teamALineup,
  teamBLineup,
  matchUrl,
}: {
  matchState: MatchState;
  teamAName: string;
  teamBName: string;
  teamALineup: string;
  teamBLineup: string;
  matchUrl?: string;
}) {
  const winnerText =
    matchState.winningTeam === 'halved'
      ? 'Match halved!'
      : `${matchState.winningTeam === 'teamA' ? teamAName : teamBName} wins ${matchState.displayScore}!`;

  const base = `${winnerText}\n${teamALineup} vs ${teamBLineup}`;
  return matchUrl ? `${base}\n\n${matchUrl}` : base;
}

export function buildPrintableMatchSummary({
  matchState,
  teamAName,
  teamBName,
  summaryText,
}: {
  matchState: MatchState;
  teamAName: string;
  teamBName: string;
  summaryText: string;
}) {
  const winnerLabel =
    matchState.winningTeam === 'halved'
      ? 'Match Halved'
      : `${matchState.winningTeam === 'teamA' ? teamAName : teamBName} Wins`;

  return `
      <html>
        <head>
          <title>Match Summary</title>
          <style>
            body { font-family: 'Plus Jakarta Sans', system-ui, sans-serif; padding: 32px; color: #1A1815; }
            .card { border: 1px solid #e5e7eb; border-radius: 16px; padding: 24px; }
            h1 { margin: 0 0 8px; font-size: 24px; }
            .score { font-size: 32px; font-weight: 700; margin: 8px 0 16px; }
            .meta { font-size: 14px; color: #4b5563; margin-top: 12px; }
            .rows { margin-top: 16px; display: grid; gap: 8px; }
            .label { font-weight: 600; }
            pre { white-space: pre-wrap; font-size: 13px; }
          </style>
        </head>
        <body>
          <div class="card">
            <h1>${winnerLabel}</h1>
            <div class="score">${matchState.displayScore}</div>
            <div class="rows">
              <div><span class="label">${teamAName}:</span> ${matchState.teamAHolesWon} holes</div>
              <div><span class="label">${teamBName}:</span> ${matchState.teamBHolesWon} holes</div>
              <div><span class="label">Halved:</span> ${countHalvedHoles(matchState)}</div>
              <div><span class="label">Completed:</span> Thru hole ${matchState.holesPlayed}</div>
            </div>
            <div class="meta">Generated by Golf Ryder Cup</div>
            <pre>${summaryText}</pre>
          </div>
        </body>
      </html>
    `;
}
