import { describe, expect, it, vi } from 'vitest';

import {
  generatePlayerStatsHTML,
  generateScorecardHTML,
  generateStandingsHTML,
} from '@/lib/services/pdf-export/pdfExportSections';
import { formatStatus, slugify } from '@/lib/services/pdf-export/pdfExportLayout';
import type {
  MatchStandingData,
  PlayerStatsData,
  ScorecardData,
  StandingsData,
} from '@/lib/services/pdfExportService';

describe('pdf export sections', () => {
  it('renders scorecard HTML with players, totals, and empty score placeholders', () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2026-03-12T12:00:00Z'));

    const data: ScorecardData = {
      tripName: 'Ryder Trip',
      courseName: 'Pine Valley',
      date: 'March 12, 2026',
      format: 'Singles',
      player1: {
        name: 'Taylor',
        team: 'USA',
        handicap: 4,
        scores: [4, 5, null, 3, 4, 5, 4, 4, 5, 4, 5, 4, 4, 5, 4, 3, 4, 5],
        frontNine: 38,
        backNine: 38,
        total: 76,
      },
      player2: {
        name: 'Shane',
        team: 'Europe',
        scores: [5, 4, 4, 4, 5, 5, 4, 5, 4, 5, 4, 5, 4, 5, 4, 4, 5, 4],
        frontNine: 40,
        backNine: 40,
        total: 80,
      },
      result: 'Taylor 2&1',
    };

    const html = generateScorecardHTML(data);

    expect(html).toContain('Scorecard - Taylor vs Shane');
    expect(html).toContain('HCP: 4');
    expect(html).toContain('<td>-</td>');
    expect(html).toContain('Taylor 2&1');
    expect(html).toContain('Generated by Golf Ryder Cup App');

    vi.useRealTimers();
  });

  it('renders standings HTML with leader state and in-progress hole formatting', () => {
    const inProgressMatch: MatchStandingData = {
      player1: 'Taylor',
      player2: 'Shane',
      team1: 'USA',
      team2: 'Europe',
      status: 'in-progress',
      currentHole: 7,
    };
    const data: StandingsData = {
      tripName: 'Ryder Trip',
      date: 'March 12, 2026',
      usaScore: 8.5,
      europeScore: 7.5,
      pointsToWin: 5.5,
      matches: [inProgressMatch],
    };

    const html = generateStandingsHTML(data);

    expect(html).toContain('team usa leading');
    expect(html).toContain('Hole 7');
    expect(html).toContain('5.5 points needed to win');
    expect(formatStatus(inProgressMatch)).toBe('Hole 7');
  });

  it('renders player stats HTML with computed win rate and stable slug formatting', () => {
    const data: PlayerStatsData = {
      playerName: 'Taylor Oneill',
      tripName: 'Ryder Trip',
      team: 'USA',
      stats: {
        matchesPlayed: 8,
        matchesWon: 5,
        matchesLost: 2,
        matchesTied: 1,
        pointsEarned: 5.5,
        averageScore: 74.2,
        bestScore: 69,
        worstScore: 82,
        birdies: 11,
        pars: 42,
        bogeys: 19,
      },
    };

    const html = generatePlayerStatsHTML(data);

    expect(html).toContain('63%');
    expect(html).toContain('Points Earned');
    expect(slugify(data.playerName)).toBe('taylor-oneill');
  });
});
