/**
 * Structural tests for the PracticeGroupsTemplate shape consumed by
 * the "Copy pairings from…" dropdown. The editor's applyTemplate
 * renumbers groups to 1..N and generates fresh localIds — these are
 * small-enough properties to exercise directly against the template
 * data without rendering the React tree.
 */

import { describe, expect, it } from 'vitest';
import type { PracticeGroupDraft } from '../lib/services/lineup-builder/practiceLineupPersistence';
import type { PracticeGroupsTemplate } from '../components/captain/lineup/PracticeGroupsEditor';

function g(source: string, number: number, players: string[]): PracticeGroupDraft {
  return { localId: `${source}-${number}`, groupNumber: number, playerIds: players, teeTime: '' };
}

describe('PracticeGroupsTemplate', () => {
  it('keeps the template sourceId distinct from its group localIds', () => {
    const template: PracticeGroupsTemplate = {
      sourceId: 'sess-1',
      label: 'Thursday practice — 3 groups',
      groups: [
        g('sess-1', 1, ['p1', 'p2']),
        g('sess-1', 2, ['p3', 'p4']),
        g('sess-1', 3, ['p5']),
      ],
    };

    // The sourceId is stable (used as React key in the select); the
    // localIds are disposable (will be regenerated by applyTemplate).
    expect(template.sourceId).toBe('sess-1');
    expect(template.groups[0]?.localId).not.toBe(template.sourceId);
  });

  it('allows an empty groups array for sessions with no published pairings yet', () => {
    const template: PracticeGroupsTemplate = {
      sourceId: 'sess-empty',
      label: 'Sunday practice — 0 groups',
      groups: [],
    };
    expect(template.groups).toHaveLength(0);
  });
});
