import { formatGeneratedOn, formatStatus, getPDFStyles } from './pdfExportLayout';
import type { PlayerStatsData, ScorecardData, StandingsData } from './pdfExportTypes';

export function generateScorecardHTML(data: ScorecardData): string {
  const holes = Array.from({ length: 18 }, (_, i) => i + 1);
  const frontHoles = holes.slice(0, 9);
  const backHoles = holes.slice(9, 18);

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Scorecard - ${data.player1.name} vs ${data.player2.name}</title>
  <style>${getPDFStyles()}</style>
</head>
<body>
  <div class="scorecard">
    <header class="header">
      <div class="header-left">
        <h1 class="title">${data.tripName}</h1>
        <p class="subtitle">${data.courseName} • ${data.date}</p>
      </div>
      <div class="header-right">
        <span class="format">${data.format}</span>
      </div>
    </header>

    <div class="players">
      <div class="player ${data.player1.team.toLowerCase()}">
        <span class="flag">${data.player1.team === 'USA' ? '🇺🇸' : '🇪🇺'}</span>
        <span class="name">${data.player1.name}</span>
        ${data.player1.handicap ? `<span class="handicap">HCP: ${data.player1.handicap}</span>` : ''}
      </div>
      <div class="vs">vs</div>
      <div class="player ${data.player2.team.toLowerCase()}">
        <span class="flag">${data.player2.team === 'USA' ? '🇺🇸' : '🇪🇺'}</span>
        <span class="name">${data.player2.name}</span>
        ${data.player2.handicap ? `<span class="handicap">HCP: ${data.player2.handicap}</span>` : ''}
      </div>
    </div>

    <table class="scores-table">
      <thead>
        <tr>
          <th>Hole</th>
          ${frontHoles.map((hole) => `<th>${hole}</th>`).join('')}
          <th class="total">Out</th>
          ${backHoles.map((hole) => `<th>${hole}</th>`).join('')}
          <th class="total">In</th>
          <th class="total">Tot</th>
        </tr>
      </thead>
      <tbody>
        <tr class="${data.player1.team.toLowerCase()}">
          <td class="player-name">${data.player1.name}</td>
          ${data.player1.scores.slice(0, 9).map((score) => `<td>${score ?? '-'}</td>`).join('')}
          <td class="total">${data.player1.frontNine}</td>
          ${data.player1.scores.slice(9, 18).map((score) => `<td>${score ?? '-'}</td>`).join('')}
          <td class="total">${data.player1.backNine}</td>
          <td class="total grand">${data.player1.total}</td>
        </tr>
        <tr class="${data.player2.team.toLowerCase()}">
          <td class="player-name">${data.player2.name}</td>
          ${data.player2.scores.slice(0, 9).map((score) => `<td>${score ?? '-'}</td>`).join('')}
          <td class="total">${data.player2.frontNine}</td>
          ${data.player2.scores.slice(9, 18).map((score) => `<td>${score ?? '-'}</td>`).join('')}
          <td class="total">${data.player2.backNine}</td>
          <td class="total grand">${data.player2.total}</td>
        </tr>
      </tbody>
    </table>

    <div class="result">
      <span class="result-label">Result:</span>
      <span class="result-value">${data.result}</span>
    </div>

    <footer class="footer">
      <p>Generated by Golf Ryder Cup App • ${formatGeneratedOn()}</p>
    </footer>
  </div>
</body>
</html>
  `;
}

export function generateStandingsHTML(data: StandingsData): string {
  const leader = data.usaScore > data.europeScore ? 'USA' : data.europeScore > data.usaScore ? 'Europe' : 'Tied';

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Standings - ${data.tripName}</title>
  <style>${getPDFStyles()}</style>
</head>
<body>
  <div class="standings">
    <header class="header">
      <h1 class="title">${data.tripName}</h1>
      <p class="subtitle">Standings as of ${data.date}</p>
    </header>

    <div class="score-display">
      <div class="team usa ${leader === 'USA' ? 'leading' : ''}">
        <span class="flag">🇺🇸</span>
        <span class="team-name">USA</span>
        <span class="score">${data.usaScore}</span>
      </div>
      <div class="divider">-</div>
      <div class="team europe ${leader === 'Europe' ? 'leading' : ''}">
        <span class="score">${data.europeScore}</span>
        <span class="team-name">Europe</span>
        <span class="flag">🇪🇺</span>
      </div>
    </div>

    <p class="points-needed">${data.pointsToWin} points needed to win</p>

    <h2>Match Results</h2>
    <table class="matches-table">
      <thead>
        <tr>
          <th>Match</th>
          <th>Status</th>
          <th>Result</th>
        </tr>
      </thead>
      <tbody>
        ${data.matches.map((match) => `
          <tr>
            <td>
              <span class="player ${match.team1.toLowerCase()}">${match.player1}</span>
              <span class="vs">vs</span>
              <span class="player ${match.team2.toLowerCase()}">${match.player2}</span>
            </td>
            <td class="status ${match.status}">${formatStatus(match)}</td>
            <td class="result">${match.result || '-'}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>

    <footer class="footer">
      <p>Generated by Golf Ryder Cup App • ${formatGeneratedOn()}</p>
    </footer>
  </div>
</body>
</html>
  `;
}

export function generatePlayerStatsHTML(data: PlayerStatsData): string {
  const winRate = data.stats.matchesPlayed > 0
    ? Math.round((data.stats.matchesWon / data.stats.matchesPlayed) * 100)
    : 0;

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Player Stats - ${data.playerName}</title>
  <style>${getPDFStyles()}</style>
</head>
<body>
  <div class="player-stats">
    <header class="header">
      <h1 class="title">${data.playerName}</h1>
      <p class="subtitle">${data.tripName} • Team ${data.team}</p>
      <span class="flag large">${data.team === 'USA' ? '🇺🇸' : '🇪🇺'}</span>
    </header>

    <div class="stats-grid">
      <div class="stat-card">
        <span class="stat-value">${data.stats.matchesPlayed}</span>
        <span class="stat-label">Matches Played</span>
      </div>
      <div class="stat-card highlight">
        <span class="stat-value">${data.stats.matchesWon}</span>
        <span class="stat-label">Wins</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">${data.stats.matchesLost}</span>
        <span class="stat-label">Losses</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">${data.stats.matchesTied}</span>
        <span class="stat-label">Ties</span>
      </div>
      <div class="stat-card large">
        <span class="stat-value">${winRate}%</span>
        <span class="stat-label">Win Rate</span>
      </div>
      <div class="stat-card large highlight">
        <span class="stat-value">${data.stats.pointsEarned}</span>
        <span class="stat-label">Points Earned</span>
      </div>
    </div>

    <h2>Scoring Statistics</h2>
    <div class="stats-grid">
      <div class="stat-card">
        <span class="stat-value">${data.stats.averageScore}</span>
        <span class="stat-label">Average Score</span>
      </div>
      <div class="stat-card good">
        <span class="stat-value">${data.stats.bestScore}</span>
        <span class="stat-label">Best Score</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">${data.stats.worstScore}</span>
        <span class="stat-label">Worst Score</span>
      </div>
    </div>

    <h2>Hole Performance</h2>
    <div class="stats-grid">
      <div class="stat-card good">
        <span class="stat-value">${data.stats.birdies}</span>
        <span class="stat-label">Birdies</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">${data.stats.pars}</span>
        <span class="stat-label">Pars</span>
      </div>
      <div class="stat-card">
        <span class="stat-value">${data.stats.bogeys}</span>
        <span class="stat-label">Bogeys+</span>
      </div>
    </div>

    <footer class="footer">
      <p>Generated by Golf Ryder Cup App • ${formatGeneratedOn()}</p>
    </footer>
  </div>
</body>
</html>
  `;
}
